version: 2.0

defaults: &defaults
  working_directory: ~/app
  context: Ripple
  docker:
    - image: cypress/base:10
      environment:
        TERM: xterm
        SEARCH_BE: LOCAL-CI

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: yarn --version
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!
      - persist_to_workspace:
          root: ~/app
          paths: .

  # Runs lint, unit tests, and basic UI tests
  test:
    <<: *defaults
    steps:    
      - attach_workspace:
          at: ~/app
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Lint code.
          command: yarn lint     
      - run:
          name: Unit tests
          command: yarn test:unit
      - run: 
          name: run smoke test
          command: yarn test:smoke
      - store_artifacts:
          path: test/e2e/videos
      - store_artifacts:
          path: test/e2e/screenshots

  # This runs the full suite of e2e tests 
  e2e:
    <<: *defaults
    steps:    
      - attach_workspace:
          at: ~/app
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run: 
          name: run full e2e test
          command: yarn test:e2e
      - store_artifacts:
          path: test/e2e/videos
      - store_artifacts:
          path: test/e2e/screenshots
  # deploy to npm step
  predeploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run: 
          name: Set NPM_TOKEN
          command: - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to NPM
          command: yarn publish --dist-tag prerelease --yes

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test:
          requires:
            - build
      # Run e2e tests on release branches
      - e2e:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
                - release/*
      - hold: # Manual approval step for deployment
          type: approval
          requires:
           - e2e
      - predeploy:
          requires:
            - build
            - test
            - e2e
          filters:
            branches:
              only:
                - release/*

  # Run full regression test nightly on develop
  nightly:
    triggers:
      - schedule:
          cron: "30 14 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - build
      - test:
          requires:
            - build
      - e2e:
          requires:
            - build
            - test
