version: 2.0

jobs:
  build:
    context: Ripple
    docker:
      - image: cypress/base:10
        environment:
          TERM: xterm
          SEARCH_BE: LOCAL-CI
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn --version
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/ripple-nuxt-tide/node_modules
            - packages/ripple-nuxt-ui/node_modules
            - packages/ripple-create-app/node_modules
            - packages/ripple-test-tools/node_modules
            - examples/vic-gov-au/node_modules
            - /root/.cache/Cypress
            - ~/.cache
      - persist_to_workspace:
          root: ~/app
          paths: .

  # Runs lint, unit tests, and basic UI tests
  test:
    docker:
      - image: cypress/base:10
        environment:
          TERM: xterm
          SEARCH_BE: LOCAL-CI
    working_directory: ~/app
    steps:    
      - attach_workspace:
          at: ~/app
      - run:
          name: Lint code.
          command: yarn lint     
      - run:
          name: Unit tests
          command: yarn test:unit
      - run: 
          name: run smoke test
          command: yarn test:smoke
      - store_artifacts:
          path: test/e2e/videos
      - store_artifacts:
          path: test/e2e/screenshots

  # This runs the full suite of e2e tests 
  e2e:
    docker:
      - image: cypress/base:10
        environment:
          TERM: xterm
          SEARCH_BE: LOCAL-CI
    working_directory: ~/app
    steps:    
      - attach_workspace:
          at: ~/app
      - run: 
          name: run full e2e test
          command: yarn test:e2e
      - store_artifacts:
          path: test/e2e/videos
      - store_artifacts:
          path: test/e2e/screenshots

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test:
          requires:
            - build
      # Run e2e tests on release branches
      - e2e:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - release/*
                - feature/SDPA-2506-circle-setup

  # Run full regression test nightly on develop
  nightly:
    triggers:
      - schedule:
          cron: "30 14 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - build
      - test:
          requires:
            - build
      - e2e:
          requires:
            - build
            - test
